name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DOCKER_REPOSITORY: devolutionary
  IMAGE_TAG: ${{ github.run_number }}

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Build the Docker image
      run: docker build ./app-dotnet --file ./app-dotnet/Dockerfile --tag webapp:$IMAGE_TAG
      
    - name: Tag the Docker image
      run: docker tag webapp:$IMAGE_TAG ${DOCKER_REPOSITORY}/webapp:$IMAGE_TAG
